import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const source=fs.readFileSync(path.join(dir,'chapters.html'),'utf8');
const chunks=source.split(/<!-- CHAPTER /).slice(1);
const chapters=chunks.map((chunk,index)=>{const end=chunk.indexOf(' -->');const [id,group,title,summary]=chunk.slice(0,end).split('|');const body=chunk.slice(end+4).trim();const words=body.replace(/<[^>]+>/g,' ').split(/\s+/).filter(Boolean).length;return {id,group,title,summary,body,index,words,time:`${Math.max(3,Math.ceil(words/180))} min`,level:group,terms:`${title} ${summary}`};});
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const render=c=>`<p class="eyebrow">${String(c.index).padStart(2,'0')} · ${escape(c.group)}</p><h1>${escape(c.title)}</h1><p class="lede">${escape(c.summary)}</p><div class="lesson-meta"><span>${c.time} read</span><span>Updated 6 September 2026</span></div>${c.body}`;
const data=JSON.stringify(chapters.map(({body,index,words,...rest})=>rest));
const guide={slug:'cyber-distillation',storageKey:'cyber-distillation-field-guide-progress-v1',title:'Cyber Model Distillation Field Guide'};
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="A comprehensive guide to Minitron pruning, Laguna MoE distillation, Qwen architecture tradeoffs, cybersecurity datasets, and training on a 64 GB Mac or RTX 4090."><meta name="theme-color" content="#a8e6b5"><title>${guide.title}</title><link rel="stylesheet" href="./base.css"><link rel="stylesheet" href="./styles.css"></head>
<body data-guide-id="cyber-distillation"><a class="skip-link" href="#lesson">Skip to lesson</a><div class="shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#orientation"><span class="brand-mark">C/</span><span><strong>Cyber Distillation</strong><small>MODELS · DATA · EVIDENCE</small></span></a><div class="progress-card"><div class="progress-copy"><span>Your progress</span><strong id="progress-label">0%</strong></div><div class="progress-track" aria-hidden="true"><i id="progress-bar"></i></div></div><nav id="course-nav" aria-label="Field guide chapters"></nav><div class="sidebar-foot"><span class="status-dot"></span>LOCAL MODELS · DEFENSIVE WORK</div></aside>
<main><header class="topbar"><button class="menu-button" id="menu-button" type="button" aria-label="Open guide navigation" aria-expanded="false">☰</button><div class="crumb" id="crumb">00 / Start here</div><button class="key-hint" id="search-button" type="button"><kbd>/</kbd> Find a chapter</button></header><div class="lesson-stage"><a class="lesson-home-grid" href="../" aria-label="Return to Field Guide Library" title="Field Guide Library"></a><article id="lesson" tabindex="-1">${render(chapters[0])}</article></div><footer class="lesson-footer"><button id="previous" class="nav-button" type="button">← Previous</button><button id="complete" class="complete-button" type="button">Mark complete</button><button id="next" class="nav-button" type="button">Next →</button></footer><noscript><p>This guide uses JavaScript for chapter navigation. <a href="./read-all.html">Read every chapter on one page.</a></p></noscript></main></div>
<dialog id="search-dialog" aria-labelledby="search-label"><div class="search-box"><button class="search-close" type="button" onclick="this.closest('dialog').close()">Close</button><label id="search-label" for="search-input">Find a chapter</label><input id="search-input" type="search" placeholder="Try MoE, same size, refusals, or training time" autocomplete="off"><div id="search-results"></div><small>Arrow keys select · Enter opens · Escape closes</small></div></dialog>
<script type="application/json" id="guide-data">${JSON.stringify(guide)}</script><script type="application/json" id="course-data">${data}</script>${chapters.map(c=>`<template id="lesson-${c.id}">${render(c)}</template>`).join('\n')}<script src="../appearance.js?v=2"></script><script src="./app.js"></script></body></html>`;
fs.writeFileSync(path.join(dir,'index.html'),html);
fs.writeFileSync(path.join(dir,'read-all.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Read all · ${guide.title}</title><link rel="stylesheet" href="./base.css"><link rel="stylesheet" href="./styles.css"></head><body><main><article id="lesson"><p><a href="./">Open the chapter guide</a> · <a href="../">Field Guide Library</a></p>${chapters.map(c=>`<section id="${c.id}">${render(c)}</section>`).join('<hr>')}</article></main></body></html>`);
console.log(JSON.stringify({chapters:chapters.length,words:chapters.reduce((n,c)=>n+c.words,0),ids:chapters.map(c=>c.id)},null,2));
