import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const source = fs.readFileSync(path.join(dir, 'chapters.html'), 'utf8');
const chapters = source.split(/<!-- CHAPTER /).slice(1).map((chunk, index) => {
  const end = chunk.indexOf(' -->');
  const [id, group, title, summary] = chunk.slice(0, end).split('|');
  const body = chunk.slice(end + 4).trim();
  const words = body.replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;
  return {id, group, title, summary, body, index, words, time: `${Math.max(3, Math.ceil(words / 180))} min`, level: group, terms: `${title} ${summary}`};
});
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const render = chapter => `<p class="eyebrow">${String(chapter.index).padStart(2, '0')} · ${escape(chapter.group)}</p><h1>${escape(chapter.title)}</h1><p class="lede">${escape(chapter.summary)}</p><div class="lesson-meta"><span>${chapter.time} read</span><span>Updated 23 September 2026</span><span class="edition-label">Tropical edition</span></div>${chapter.body}`;
const guide = {slug: 'gemma-cyber-training', storageKey: 'gemma-cyber-training-progress-v1', title: 'Gemma Training Field Guide'};
const data = JSON.stringify(chapters.map(({body, index, words, ...rest}) => rest)).replaceAll('<', '\\u003c');
const styles = '<link rel="stylesheet" href="./base.css"><link rel="stylesheet" href="./styles.css?v=1"><link rel="stylesheet" href="../layout.css"><link rel="stylesheet" href="./tropical.css?v=2">';
const head = title => `<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="A practical Gemma 3 27B field guide to continued pretraining, instruction tuning, personality, defensive security datasets, evaluation, rented GPUs, and costs."><meta name="theme-color" content="#34d5c0"><title>${escape(title)}</title>${styles}`;
const html = `<!doctype html>
<html lang="en"><head>${head(guide.title)}</head>
<body data-guide-id="gemma-cyber-training"><a class="skip-link" href="#lesson">Skip to lesson</a><div class="shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#orientation"><span class="brand-mark">G/</span><span><strong>Gemma Training</strong><small>KNOWLEDGE · JUDGMENT · VOICE</small></span></a><div class="progress-card"><div class="progress-copy"><span>Your progress</span><strong id="progress-label">0%</strong></div><div class="progress-track" aria-hidden="true"><i id="progress-bar"></i></div></div><nav id="course-nav" aria-label="Field guide chapters"></nav><div class="sidebar-links"><a href="./read-all.html">Read every chapter ↗</a><a href="../">← Field Guide Library</a></div><div class="sidebar-foot"><span class="status-dot"></span>GEMMA 3 · CPT · SFT · RENTED GPUS</div></aside>
<main><header class="topbar"><button class="menu-button" id="menu-button" type="button" aria-label="Open guide navigation" aria-expanded="false">☰</button><div class="crumb" id="crumb">00 / Knowledge and behavior</div><div class="topbar-actions"><a class="read-all-link" href="./read-all.html">Read all</a><button class="key-hint" id="search-button" type="button"><kbd>/</kbd> Find a chapter</button></div></header><div class="lesson-stage"><a class="lesson-home-grid" href="../" aria-label="Return to Field Guide Library" title="Field Guide Library"></a><article id="lesson" tabindex="-1">${render(chapters[0])}</article></div><footer class="lesson-footer"><button id="previous" class="nav-button" type="button">← Previous</button><button id="complete" class="complete-button" type="button">Mark complete</button><button id="next" class="nav-button" type="button">Next →</button></footer><noscript><p class="noscript-note">Use <a href="./read-all.html">Read every chapter on one page</a> to read the guide without JavaScript.</p></noscript></main></div>
<dialog id="search-dialog" aria-labelledby="search-label"><div class="search-box"><button class="search-close" type="button" onclick="this.closest('dialog').close()">Close</button><label id="search-label" for="search-input">Find a chapter</label><input id="search-input" type="search" placeholder="Try CPT, personality, QLoRA, Runpod, or cost" autocomplete="off"><div id="search-results"></div><small>Arrow keys select · Enter opens · Escape closes</small></div></dialog>
<script type="application/json" id="guide-data">${JSON.stringify(guide)}</script><script type="application/json" id="course-data">${data}</script>${chapters.map(chapter => `<template id="lesson-${chapter.id}">${render(chapter)}</template>`).join('\n')}<script src="../appearance.js?v=3"></script><script src="./calculator.js"></script><script src="./app.js"></script></body></html>`;
fs.writeFileSync(path.join(dir, 'index.html'), html);
const readAll = `<!doctype html><html lang="en"><head>${head(`Read all · ${guide.title}`)}</head><body class="read-all" data-guide-id="gemma-cyber-training"><a class="skip-link" href="#lesson">Skip to guide</a><main><header class="read-all-header"><a href="./">← Chapter guide</a><span>Tropical edition</span><a href="../">Field Guide Library ↗</a></header><article id="lesson" tabindex="-1"><nav class="read-all-toc" aria-label="All chapters"><p class="eyebrow">Read at your own pace</p><h1>Gemma Training<br>Field Guide</h1><p class="lede">Domain knowledge, problem-solving approach, personality, and rented GPU practice.</p><ol>${chapters.map(chapter => `<li><a href="#${chapter.id}">${escape(chapter.title)}</a></li>`).join('')}</ol></nav>${chapters.map(chapter => `<section id="${chapter.id}" class="read-all-chapter">${render(chapter)}</section>`).join('<hr>')}</article></main><script src="../appearance.js?v=3"></script><script src="./calculator.js"></script></body></html>`;
fs.writeFileSync(path.join(dir, 'read-all.html'), readAll);
console.log(JSON.stringify({chapters: chapters.length, words: chapters.reduce((total, chapter) => total + chapter.words, 0), ids: chapters.map(chapter => chapter.id)}, null, 2));
